[package]
name = "grrs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.0",features = ["derive"]}
anyhow ={ version = "1.0" }
indicatif = {version ="0.17.1"}

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
assert_fs = "1.1.1"

